shop_parser/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls') )
]


if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

shop_parser/main/urls.py
from django.urls import path

from .views import index, other_page, ShopsLoginView, ShopsLogoutView, ChangeUserInfoView, ChangeUserPasswordView, user_goods, RegisterUserView, RegisterDoneView, DeleteUserView

app_name = 'main'
urlpatterns = [
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/register_done', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/login/', ShopsLoginView.as_view(), name='login'),
    path('accounts/password_change/', ChangeUserPasswordView.as_view(), name='password_change'),
    path('acoounts/logout/', ShopsLogoutView.as_view(), name='logout'),
    path('acounts/delete_user/', DeleteUserView.as_view(), name='delete_user'),
    path('accounts/user_goods/', user_goods, name='user_goods'),
    path("accounts/profile/", ChangeUserInfoView.as_view(), name="profile"),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index')
]

shop_parser/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    '''Модель пользователя'''
    send_messages = models.BooleanField(default=False, verbose_name='Получать уведомления?')
    
    class Meta(AbstractUser.Meta):
        pass

shop_parser/main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import User

class LoginForm(forms.Form):
    user_name = forms.CharField(required=True, label='Имя пользователя')
    password = forms.PasswordInput()
    
class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Ваш email')
    password_1 = forms.CharField(label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password_2 = forms.CharField(label='Пароль (повторно)',widget=forms.PasswordInput, help_text='Введите ваш пароль повторно')
    
    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password_1']
        password_2 = self.cleaned_data['password_2']
        if password_1 and password_2 and password_1 != password_2:
            errors = {'password_2': ValidationError ('Пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)
        
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['username']
        user.set_password(self.cleaned_data['password_1'])
        user.is_active = True
        user.is_activated = True
        user.send_messages = False
        user.save()
        
        return user
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password_1', 'password_2')
        
        
class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')
    
    class Meta:
        model = User
        fields = ('username', 'email', 'send_messages')

shop_parser/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib import messages

from .models import User
from .forms import RegisterUserForm, ChangeUserInfoForm

def index(request):
    return render(request, 'main/index.html')

def other_page(request, page):
    """Проверка наличия шаблона"""
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

@login_required
def user_goods(request):
    return render(request, 'main/user_goods.html')

class ShopsLoginView(LoginView):
    model = User
    fields = ['name', 'password']
    template_name = 'main/login.html'
    success_url = reverse_lazy('main:index')
    
class ShopsLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'
    
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    form_class = ChangeUserInfoForm
    template_name = 'main/profile.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Настройки изменены'
    
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)
    
class ChangeUserPasswordView(PasswordChangeView, LoginRequiredMixin, SuccessMessageMixin):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль изменен'
    
class RegisterUserView(CreateView):
    model = User
    template_name = 'main/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')
    
class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'
    
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')
    
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    
    def logout_user(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
            
        return get_object_or_404(queryset, pk=self.user_id)

shop_parser/main/templates/main/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo"><h1>Logo</h1></div>
            <div class="theme_button">
                <a href="#"><img src="{% static 'main/img/theme.png' %}" alt="Смена темы" class="theme_icon"></a>
            </div>
        </div>
        <div class="sorting_buttons">
            <ul class="sorting_buttons_list">
                <li class="sort_button"><a href="#">Все товары</a></li>
                <li class="sort_button"><a href="#">Самые подорожавшие</a></li>
                <li class="sort_button"><a href="#">Самые подешевевшие</a></li>
                <li class="sort_button"><a href="#">Категория ↑</a></li>
                <li class="sort_button"><a href="#">Категория ↓</a></li>
            </ul>
        </div>
        <div class="marketplace_buttons">
            <ul class="marketplace_buttons_list">
                <li class="market_button" ><a href="#">Все магазины</a></li>
                <li class="market_button" ><a href="#">Ozon</a></li>
                <li class="market_button" ><a href="#">Перекресток</a></li>
                <li class="market_button" ><a href="#">Wildberrys</a></li>
            </ul>
        </div>
        <div class="messages">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">
                            {{ message|safe }}
                            <a href="#" class="close">✖</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        {% block content %}{% endblock %}
        <div class="login_button">
            {% if user.is_authenticated %}
            {% if request.path != '/accounts/user_goods/' %}
                <p><a href="{% url 'main:user_goods' %}">Ваши товары</a></p>
            {% endif %}
            {% if request.path != '/accounts/profile/' %}
                <p><a href="{% url 'main:profile' %}">Профиль {{ user.username }}</a></p>
            {% endif %}
                <p><a href="{% url 'main:logout' %}">Выход</a></p>
            {% else %}
                {% if request.path != '/accounts/login/' %}
                    <a href="{% url 'main:login' %}">Вход</a>
                {% endif %}
            {% endif %}
        </div>
        <footer>
            <div class="footer_container">
                <p class="copyrights">Создано <a href="#">Espadane</a> при неоценимой поддержке <a href="#">Марковки</a></p>
            </div>
        </footer>
    </div>
</body>
</html>

shop_parser/main/templates/main/delete_user.html
{% extends 'main/basic.html' %}

{% block title %}
    Удаление аккаунта
{% endblock %}

{% block content %}
    <h2>Удаление аккаунта {{ object.name }}</h2>
    <p>Вы уверены что хотите удалить аккаунт?</p>
    <p>Это действие необратимо. Ваши товары которые вы отслеживаете так же удалятся.</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'main:index' %}">Нет, вернуться на главную</a>
        <button type="submit">Да уверен, удалить</button>
    </form>
{% endblock %}

shop_parser/main/templates/main/index.html
{% extends 'main/basic.html' %}

{% block title %}
    Потребительская корзина
{% endblock %}

{% block buttons %}{% endblock %}


{% block content %}
    <h2>Тут будут карточки товаров</h2>
    <ul>
        <li>карточка</li>
        <li>карточка</li>
        <li>карточка</li>
        <li>карточка</li>
        <li>карточка</li>
        <li>карточка</li>
    </ul>
    
{% endblock %}

shop_parser/main/templates/main/login.html
{% extends 'main/basic.html' %}

{% block title %}
    Вход
{% endblock %}

{% block content %}
    <h2>Вход на сайт</h2>
    {% if user.is_authenticated %}
        <p>Вы уже вошли</p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Войти</button>
        </form>
        <input type="hidden" name="next" value="{{ next }}">
        <button type="submit">Войти</button>
        <p>Нет учетной записи? <a href="{% url 'main:register' %}">Регистрация</a></p>
    {% endif %}
{% endblock %}

shop_parser/main/templates/main/logout.html
{% extends 'main/basic.html' %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта</p>

{% endblock %}

shop_parser/main/templates/main/password_change.html
{% extends 'main/basic.html' %}

{% block title %}
    Смена пароля
{% endblock %}

{% block content %}
    <h2>Смена пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Сменить пароль</button>
    </form>
    
{% endblock %}

shop_parser/main/templates/main/profile.html
{% extends 'main/basic.html' %}

{% block title %}
    Настройки профиля
{% endblock %}

{% block content %}
    <h2>Настройки профиля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Сохранить</button>
    </form>
    <a href="{% url 'main:password_change' %}">Сменить пароль</a>
    <a href="{% url 'main:delete_user' %}">Удалить аккаунт</a>
{% endblock %}

shop_parser/main/templates/main/register.html
{% extends 'main/basic.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Подтвердить</button>
    </form>
{% endblock %}

shop_parser/main/templates/main/register_done.html
{% extends 'main/basic.html' %}

{% block title %}
    Успешно
{% endblock %}

{% block content %}
    <h2>Регистрация успешно выполнена</h2>
{% endblock %}

shop_parser/main/templates/main/user_goods.html
{% extends 'main/basic.html' %}

{% block content %}
    <h1>Тут будут карточки с товарами пользователя</h1>
{% endblock %}